# 실행에서 제외할 룰 식별자
disabled_rules:
- line_length
- trailing_whitespace
- identifier_name
- function_parameter_count
- file_length
- function_body_length
- nesting
# 린트 과정에서 무시할 파일 경로
excluded:
- Clone-Weather/Application/AppDelegate.swift
- Clone-Weather/Application/SceneDelegate.swift
